<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>PNCPGuard</AssemblyName>
    <RootNamespace>PNCPKing.Guard</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PNCPKing.Core/PNCPKing.Core.csproj"
                      SkipGetTargetFrameworkProperties="true" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
