<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Geography/BrazilMunicipalities2022.csv.gz.b64"
                      LogicalName="PNCPKing.Core.Geography.BrazilMunicipalities2022.csv.gz.b64" />
  </ItemGroup>
</Project>
