<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>PNCPKing</AssemblyName>
    <RootNamespace>PNCPKing.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PNCPKing.Infrastructure/PNCPKing.Infrastructure.csproj"
                      SkipGetTargetFrameworkProperties="true" />
    <PackageReference Include="Tesseract" />
    <PackageReference Include="PDFtoImage" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets/tessdata/por.traineddata"
                      LogicalName="PNCPKing.App.Assets.tessdata.por.traineddata" />
  </ItemGroup>
</Project>
